name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install codespell
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --dev --python=3.10
          uv add codespell

      - name: Run codespell
        run: |
          source .venv/bin/activate
          codespell -L "ocassion,occassion,ot,te,tje" **/*.{txt,md,py,ipynb}

  required-checks:
    name: Required checks
    runs-on: ubuntu-latest
    needs:
      - spellcheck
    if: always()
    steps:
      - name: Check required jobs
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || \
                "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
