name: Sync Fork

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Forks Sync Action
        uses: TobKed/github-forks-sync-action@v0.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: rasbt/LLMs-from-scratch
          upstream_branch: main
          target_branch: main
          force: false
